docMaker: docMaker.cpp
	mpic++ -o docMaker docMaker.cpp -std=c++11
indexer: indexer.cpp
	mpic++ -o indexer indexer.cpp -std=c++11
indexMerger: indexMerger.cpp
	mpic++ -o indexMerger indexMerger.cpp -std=c++11
clean: *
	rm *
